Repository pyscript/pyscript, pull requests merged in 2022-11, with the labels that each got.

#914 implement proposal for fetching paths and retaining structure of dirs and packages
  docs/guides/http-requests.md
  docs/reference/elements/py-config.md
  docs/reference/elements/py-script.md
  docs/tutorials/getting-started.md
  examples/antigravity.html
  examples/numpy_canvas_fractals.html
  examples/repl.html
  examples/repl2.html
  examples/simple_clock.html
  examples/todo-pylist.html
  examples/todo.html
  pyscriptjs/Makefile
  pyscriptjs/src/main.ts
  pyscriptjs/src/plugins/fetch.ts
  pyscriptjs/src/pyconfig.ts
  pyscriptjs/src/pyodide.ts
  pyscriptjs/src/runtime.ts
  pyscriptjs/src/utils.ts
  pyscriptjs/tests/integration/test_01_basic.py
  pyscriptjs/tests/integration/test_py_config.py
  pyscriptjs/tests/unit/fakeruntime.ts
  pyscriptjs/tests/unit/fetch_plugin.test.ts
  pyscriptjs/tests/unit/pybox.test.ts
  pyscriptjs/tests/unit/pybutton.test.ts
  pyscriptjs/tests/unit/pyconfig.test.ts
  pyscriptjs/tests/unit/pytitle.test.ts
  pyscriptjs/tests/unit/utils.test.ts
Labels: sprint

#926 decode innerhtml for pyconfig
  pyscriptjs/src/pyconfig.ts
Labels: sprint

#927 use user error for paths calculation
  pyscriptjs/src/plugins/fetch.ts
Labels: sprint

#929 add test for not escaping characters in pyconfig
  pyscriptjs/tests/unit/pyconfig.test.ts
Labels: sprint

#945 remove unneeded import
  pyscriptjs/src/main.ts
Labels: sprint

#946 remove one more unneeded import
  pyscriptjs/src/plugin.ts
Labels: sprint

#948 use a const for run button svg
  pyscriptjs/src/components/pyrepl.ts
  pyscriptjs/src/consts.ts
  pyscriptjs/src/exceptions.ts
Labels: sprint

#928 Remove 'Implicit Async', Don't Await `runtime.run()`
  docs/guides/asyncio.md
  docs/guides/index.md
  docs/index.md
  examples/bokeh_interactive.html
  examples/numpy_canvas_fractals.html
  examples/webgl/raycaster/index.html
  pyscriptjs/src/components/pyrepl.ts
  pyscriptjs/src/components/pyscript.ts
  pyscriptjs/src/pyexec.ts
  pyscriptjs/src/pyodide.ts
  pyscriptjs/src/python/pyscript.py
  pyscriptjs/src/runtime.ts
  pyscriptjs/tests/integration/test_03_async.py
  pyscriptjs/tests/integration/test_importmap.py
  pyscriptjs/tests/integration/test_py_config.py
  pyscriptjs/tests/integration/test_py_repl.py
  pyscriptjs/tests/py-unit/test_pyscript.py
Labels: status: ready

#958 Import PyScript Version into Python Runtime
  docs/reference/API/__version__.md
  docs/reference/API/versIon_info.md
  pyscriptjs/__mocks__/_pyscript.js
  pyscriptjs/__mocks__/fileMock.js
  pyscriptjs/jest.config.js
  pyscriptjs/src/pyodide.ts
  pyscriptjs/src/python/pyscript.py
  pyscriptjs/tests/integration/test_01_basic.py
  pyscriptjs/tests/py-unit/test_pyscript.py
Labels: help wanted

#991 remove unneeded imports
  pyscriptjs/src/pyodide.ts
Labels: sprint

#997 add docstrings for loadFromFile
  pyscriptjs/src/pyodide.ts
Labels: sprint
