Repository pyscript/pyscript, pull requests merged in 2022-08, with the labels that each got.

#676 Use the new testing machinery for test_examples
  pyscriptjs/tests/support.py
  pyscriptjs/tests/test_examples.py
  pyscriptjs/tests/test_zz_examples.py
  setup.cfg
Labels: sprint

#684 Ensure that angle brackets in pyscript tag are escaped before parsing
  pyscriptjs/src/utils.ts
  pyscriptjs/tests/test_01_basic.py
Labels: type: bug

#721 Fix and enable integration tests in CI
  .github/workflows/build-unstable.yml
  pyscriptjs/Makefile
  pyscriptjs/src/pyodide.ts
Labels: sprint

#738 Remove workaround for sed and upgrade pyodide to 0.21.2
  pyscriptjs/Makefile
  pyscriptjs/package-lock.json
  pyscriptjs/package.json
  pyscriptjs/src/pyodide.ts
Labels: sprint

#695 [WIP] Actions workflow cleanup/readability
  .github/workflows/build-unstable.yml
Labels: tag: tooling

#734 add tests for runtime config inside py-config and remove usage of indexURL
  examples/webgl/raycaster/index.html
  pyscriptjs/src/pyodide.ts
  pyscriptjs/src/utils.ts
  pyscriptjs/tests/integration/support.py
  pyscriptjs/tests/integration/test_py_runtime_config.py
  pyscriptjs/tests/unit/pyconfig.test.ts
  pyscriptjs/tests/unit/runtime.test.ts
Labels: sprint
