Repository pyscript/pyscript, pull requests merged in 2022-12, with the labels that each got.

#1018 Fix clashing test names
  pyscriptjs/tests/integration/test_02_display.py
  pyscriptjs/tests/integration/test_03_element.py
  pyscriptjs/tests/integration/test_async.py
  pyscriptjs/tests/integration/test_runtime.py
  pyscriptjs/tests/integration/test_style.py
Labels: sprint

#1022 split py-config into sections
  docs/reference/elements/py-config.md
Labels: sprint

#1019 updated docs for fetch
  docs/reference/elements/py-config.md
Labels: sprint

#1024 add reference to Jeff's blog
  docs/reference/elements/py-config.md
Labels: sprint

#1036 remove fetching of pyscript.py from tutorial
  docs/tutorials/py-config-fetch.md
Labels: sprint

#1041 getPySrc should return source code
  pyscriptjs/src/components/pyscript.ts
  pyscriptjs/tests/integration/test_01_basic.py
Labels: sprint

#1045 Adjust `test_version_info` - no dot in releaselevel
  pyscriptjs/tests/integration/test_01_basic.py
Labels: tag: tests

#1064 Don't add Python Plugins to Manager Twice
  pyscriptjs/src/python/pyscript.py
  pyscriptjs/tests/integration/test_plugins.py
Labels: tag: plugins
