Repository pyscript/pyscript, pull requests merged in 2022-05, with the labels that each got.

#64 Improvements to `numpy_canvas_fractals` example
  pyscriptjs/examples/fractals.py
  pyscriptjs/examples/numpy_canvas_fractals.html
Labels: type: enhancement, status: ready

#73 Update README.md: fix typos
  README.md
Labels: status: accepted, tag: docs

#101 Fixing typescript error in build process
  pyscriptjs/src/components/pybox.ts
Labels: status: accepted

#83 Create .gitkeep
  pyscriptjs/public/.gitkeep
Labels: tag: environment, status: ready

#93 add classname dynamically in examples
  pyscriptjs/examples/utils.py
Labels: status: accepted, tag: example

#96 Fix minor typo
  GETTING-STARTED.md
Labels: status: accepted, tag: docs

#127 Fix grammar in README
  README.md
Labels: status: accepted, tag: docs

#126 Fix capitalization
  pyscriptjs/examples/panel_deckgl.html
Labels: status: accepted, tag: example

#118 remove unused imports
  pyscriptjs/src/components/pyenv.ts
  pyscriptjs/src/components/pytitle.ts
  pyscriptjs/src/pyscript.py
Labels: status: accepted

#119 CSS property type
  pyscriptjs/examples/numpy_canvas_fractals.html
Labels: status: accepted, tag: example

#72 README and getting started updates
  GETTING-STARTED.md
  README.md
Labels: status: ready, tag: docs

#88 Fix absolute path when import `.py` files in examples
  pyscriptjs/examples/antigravity.html
  pyscriptjs/examples/numpy_canvas_fractals.html
  pyscriptjs/examples/repl.html
  pyscriptjs/examples/repl2.html
  pyscriptjs/examples/simple_clock.html
  pyscriptjs/examples/todo-pylist.html
  pyscriptjs/examples/todo.html
Labels: status: accepted, tag: example

#144 duplicate line
  GETTING-STARTED.md
Labels: status: accepted, tag: docs

#133 Get the GETTING-STARTED link work
  README.md
Labels: status: accepted

#150 Hotfix for py-script/py-repl loading
  pyscriptjs/examples/pylist.py
  pyscriptjs/examples/repl2.html
  pyscriptjs/examples/simple_clock.html
  pyscriptjs/examples/todo-pylist.html
  pyscriptjs/src/components/base.ts
Labels: tag: interpreter, status: ready

#130 Fix dedenting of <py-script> code
  pyscriptjs/src/utils.ts
Labels: status: ready

#121 Handle __repr__ of types
  pyscriptjs/src/interpreter.ts
  pyscriptjs/src/pyscript.py
Labels: status: accepted

#231 Add initial dev setup automation
  .pre-commit-config.yaml
  pyscriptjs/Makefile
  pyscriptjs/environment.yml
Labels: tag: environment, status: ready

#235 add config file for pre-commit
  .pre-commit-config.yaml
  pyscriptjs/examples/antigravity.py
  pyscriptjs/examples/fractals.py
  pyscriptjs/examples/palettes.py
  pyscriptjs/examples/pylist.py
  pyscriptjs/examples/todo.py
  pyscriptjs/examples/toga/freedom/src/freedom/__main__.py
  pyscriptjs/examples/toga/freedom/src/freedom/app.py
  pyscriptjs/examples/toga/server/demo.py
  pyscriptjs/examples/utils.py
  pyscriptjs/src/pyscript.py
Labels: tag: infra, tag: tests

#116 Micrograd example
  pyscriptjs/examples/micrograd_ai.html
  pyscriptjs/examples/micrograd_ai.py
Labels: status: accepted, tag: example

#131 ADD: Simple Bioinformatics Tool
  pyscriptjs/examples/simple_bioinformatics_tool.html
Labels: status: accepted, tag: example

#224 Add links to the libraries used in the examples
  pyscriptjs/examples/index.html
Labels: status: accepted, tag: example

#207 Moves Python code out of interpreter file
  pyscriptjs/Makefile
  pyscriptjs/environment.yml
  pyscriptjs/examples/micrograd_ai.py
  pyscriptjs/package-lock.json
  pyscriptjs/package.json
  pyscriptjs/rollup.config.js
  pyscriptjs/src/App.svelte
  pyscriptjs/src/components/base.ts
  pyscriptjs/src/components/pybox.ts
  pyscriptjs/src/components/pyenv.ts
  pyscriptjs/src/components/pyrepl.ts
  pyscriptjs/src/components/pyscript.ts
  pyscriptjs/src/interpreter.ts
  pyscriptjs/src/pyscript.py
Labels: tag: interpreter, status: accepted

#236 CI Improvements; more focused runs and best practices
  .github/workflows/build.yml
  .github/workflows/lint.yml
Labels: tag: infra, tag: tests

#241 Add keypress event to todo example
  pyscriptjs/examples/todo.py
Labels: status: accepted, tag: example

#211 Changed variable names to snake_case for PEP8 formatting
  pyscriptjs/examples/todo.py
  pyscriptjs/examples/utils.py
  pyscriptjs/src/pyscript.py
Labels: status: accepted, tag: example

#242 Add missing type annotations
  pyscriptjs/src/stores.ts
Labels: status: accepted, lang: typescript

#227 made py-button styling dynamic
  pyscriptjs/package-lock.json
  pyscriptjs/src/components/pybutton.ts
Labels: tag: styling, status: ready, lang: typescript

#219 Changed wallis to computepi for better description
  GETTING-STARTED.md
Labels: status: accepted, tag: docs

#282 GitHub Actions: Test on current Node.js
  .github/workflows/build.yml
  .github/workflows/lint.yml
Labels: tag: tooling

#275 Adding `textwrap.dedent` for allowing indented html blocks
  pyscriptjs/src/pyscript.py
Labels: status: accepted

#294 Fix ESLint warnings
  pyscriptjs/src/components/pybutton.ts
Labels: tag: tests

#307 Split build jobs, add S3 push
  .github/workflows/build-alpha.yml
  .github/workflows/build-latest.yml
  .github/workflows/sync-examples.yml
Labels: tag: tooling

#279 add app loading splash screen and AppConfig
  pyscriptjs/examples/simple_clock.html
  pyscriptjs/src/App.svelte
  pyscriptjs/src/components/pyconfig.ts
  pyscriptjs/src/components/pyloader.ts
  pyscriptjs/src/main.ts
  pyscriptjs/src/stores.ts
Labels: tag: styling, status: ready, tag: component

#320 Fix `<py-repl theme="dark">`
  pyscriptjs/src/components/pyrepl.ts
Labels: tag: styling, status: accepted

#328 support different pyodide versions
  pyscriptjs/examples/simple_clock.html
  pyscriptjs/src/App.svelte
  pyscriptjs/src/components/pyconfig.ts
  pyscriptjs/src/interpreter.ts
  pyscriptjs/src/main.ts
  pyscriptjs/src/stores.ts
  pyscriptjs/tsconfig.json
Labels: tag: environment, status: ready

#341 Avoid using a deprecated method
  pyscriptjs/src/interpreter.ts
Labels: tag: interpreter, status: ready

#368 remove prod flag from build cmd and add alternative build-min cmd
  pyscriptjs/package.json
Labels: tag: tooling

#397 fix autogenerated element
  pyscriptjs/examples/todo.html
  pyscriptjs/rollup.config.js
  pyscriptjs/src/components/base.ts
Labels: status: ready, tag: component

#262 Documentation infrastructure.
  .github/workflows/docs-latest.yml
  .github/workflows/docs-release.yml
  .github/workflows/docs-review.yml
  .gitignore
  .pre-commit-config.yaml
  .readthedocs.yml
  CODE_OF_CONDUCT.md
  GOVERNANCE.md
  MAINTAINERS.md
  README.md
  docs/Makefile
  docs/README.md
  docs/_static/examples/what-is-pyscript.html
  docs/_static/fonts/Hack-Bold.woff
  docs/_static/fonts/Hack-BoldItalic.woff
  docs/_static/fonts/Hack-Italic.woff
  docs/_static/fonts/Hack-Regular.woff
  docs/_static/images/avatar.jpg
  docs/_static/redirect.html
  docs/concepts/governance/maintainers.md
  docs/concepts/governance/policy.md
  docs/concepts/index.md
  docs/concepts/what-is-pyscript.md
  docs/conf.py
  docs/environment.yml
  docs/howtos/index.md
  docs/index.md
  docs/make.bat
  docs/reference/index.md
  docs/robots.txt
  docs/tutorials/deployment.md
  docs/tutorials/getting-started.md
  docs/tutorials/index.md
  docs/tutorials/setup.md
Labels: tag: docs

#372 fixed REPL bugs
  pyscriptjs/src/components/base.ts
  pyscriptjs/src/components/pyrepl.ts
  pyscriptjs/src/utils.ts
Labels: waiting on reporter, tag: component

#403 Embedding video, adding PS tag definitions
  docs/concepts/what-is-pyscript.md
  docs/conf.py
  docs/environment.yml
  docs/tutorials/getting-started.md
Labels: status: accepted, tag: docs

#355 Basic tests
  pyscriptjs/Makefile
  pyscriptjs/environment.yml
  pyscriptjs/tests/__init__.py
  pyscriptjs/tests/conftest.py
  pyscriptjs/tests/test_examples.py
Labels: status: ready, tag: tests

#417 add components description in getting started
  docs/tutorials/getting-started.md
Labels: tag: docs

#458 Update panel examples to panel 0.13.1
  pyscriptjs/examples/panel.html
  pyscriptjs/examples/panel_deckgl.html
  pyscriptjs/examples/panel_kmeans.html
  pyscriptjs/examples/panel_stream.html
Labels: status: ready, tag: example

#254 update README.md and CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: tag: docs

#466 Fixed typo in getting-started.md
  docs/tutorials/getting-started.md
Labels: tag: docs
