Repository pyscript/pyscript, pull requests merged in 2023-05, with the labels that each got.

#1374 [Worker support] test for no cors headers
  pyscriptjs/src/main.ts
  pyscriptjs/tests/integration/conftest.py
  pyscriptjs/tests/integration/support.py
  pyscriptjs/tests/integration/test_00_support.py
  pyscriptjs/tests/integration/test_01_basic.py
Labels: sprint

#1465 fix panel kmeans test
  examples/panel_kmeans.html
Labels: sprint

#1477 Fix Examples Tests in CI (Pin `pytest=7.1.2` et al)
  pyscriptjs/environment.yml
Labels: type: bug, tag: tests

#1347 Upgrade to Pyodide 0.23
  .github/workflows/build-unstable.yml
  docs/changelog.md
  docs/development/developing.md
  docs/tutorials/py-config-interpreter.md
  pyscriptjs/Makefile
  pyscriptjs/environment.yml
  pyscriptjs/package-lock.json
  pyscriptjs/package.json
  pyscriptjs/src/pyconfig.ts
  pyscriptjs/src/remote_interpreter.ts
  pyscriptjs/tests/integration/support.py
  pyscriptjs/tests/integration/test_01_basic.py
  pyscriptjs/tests/integration/test_py_config.py
  pyscriptjs/tests/integration/test_zz_examples.py
  pyscriptjs/tests/integration/test_zzz_docs_snippets.py
Labels: tag: pyodide
