Repository pyscript/pyscript, pull requests merged in 2023-04, with the labels that each got.

#1373 remove PY_COMPLETE and the associated message of `Python initialization complete`
  pyscriptjs/src/plugins/pyterminal.ts
  pyscriptjs/src/remote_interpreter.ts
  pyscriptjs/tests/integration/support.py
  pyscriptjs/tests/integration/test_01_basic.py
  pyscriptjs/tests/integration/test_02_display.py
  pyscriptjs/tests/integration/test_03_element.py
  pyscriptjs/tests/integration/test_async.py
  pyscriptjs/tests/integration/test_importmap.py
  pyscriptjs/tests/integration/test_interpreter.py
  pyscriptjs/tests/integration/test_py_config.py
  pyscriptjs/tests/integration/test_py_repl.py
  pyscriptjs/tests/integration/test_py_terminal.py
  pyscriptjs/tests/integration/test_splashscreen.py
  pyscriptjs/tests/integration/test_zzz_docs_snippets.py
Labels: sprint

#1323 Improve `validate()` function for plugin options
  pyscriptjs/src/plugin.ts
  pyscriptjs/src/plugins/pyterminal.ts
  pyscriptjs/tests/unit/plugin.test.ts
Labels: status: ready

#1413 Add `nodejs=16` to docs conda environment
  docs/environment.yml
Labels: tag: docs
